<#
.SYNOPSIS
    Read-only report that verifies the TRUE state of Microsoft Defender Antivirus,
    to distinguish it from Microsoft's confirmed false "Microsoft Defender Antivirus
    is turned off" notification bug (Windows release health, opened 2026-08-28).

.DESCRIPTION
    Since late August 2026, Windows Security has been showing a "Turn on virus
    protection" / "Microsoft Defender Antivirus is turned off" notification on
    devices where the antivirus is actually still running normally. Microsoft
    confirmed this on the Windows 11 24H2 and 25H2 release health pages as a
    genuine bug in the notification/health-reporting layer, not in real-time
    protection itself, and has not yet shipped a fix.

    This script checks THREE independent sources of truth and reports whether
    they agree that Defender Antivirus protection is genuinely healthy:

      1. Get-MpComputerStatus  - queries the MSFT_MpComputerStatus WMI class,
         a direct read from the Defender Antivirus engine/service itself.
      2. Get-Service WinDefend - confirms the underlying Windows service is
         actually running, independent of anything Defender's own health
         reporting says about itself.
      3. The Windows Defender Operational event log - scanned for Event ID
         5001 (MALWAREPROTECTION_RTP_DISABLED - "Real-time protection is
         disabled") and Event ID 5013 (Tamper Protection blocked a change)
         within a configurable lookback window. Absence of both is strong
         evidence that real-time protection was never actually turned off
         and that no tampering attempt was blocked.

    This script is entirely READ-ONLY. It does not call Set-MpPreference or
    any other state-changing cmdlet, and it does not interact with, dismiss,
    or suppress the notification itself - Windows does not expose a supported
    API for that, and none is used here.

    There is deliberately no companion "Remediate" script for this topic.
    A genuinely healthy device has nothing to remediate, and Microsoft's own
    fix will land through a future Microsoft Defender Antivirus platform or
    engine update, not through a local admin script. If this script reports
    UNHEALTHY, that is a real Defender issue independent of the notification
    bug and should be handled with your normal incident response.

.PARAMETER LookbackHours
    How many hours back to scan the Windows Defender Operational event log
    for Event ID 5001 / 5013. Default is 24.

.PARAMETER CsvPath
    Optional path to append one CSV row with this run's result, so a
    helpdesk team can build an audit trail of "checked, confirmed healthy"
    against tickets generated by the false notification.

.EXAMPLE
    .\Get-DefenderTrueStatusReport.ps1

    Runs all three checks with the default 24-hour event log lookback and
    prints a human-readable report to the console.

.EXAMPLE
    .\Get-DefenderTrueStatusReport.ps1 -LookbackHours 72 -CsvPath C:\Reports\defender-check.csv

    Widens the event log lookback to 72 hours and appends the result to a
    CSV file for tracking over time.

.OUTPUTS
    Console report. Exit code 0 if all checks report healthy, 1 if any
    check reports a genuine problem, 2 if the script itself failed to run
    (e.g. Defender module unavailable, access denied).

.NOTES
    Blog post   : https://endpointweekly.com/blog/defender-antivirus-shows-off-real-status-verification.html
    Script repo : https://github.com/Imran76Awan/Windows-Patching-Scripts
    Author      : EndpointWeekly
    Requires    : Windows PowerShell 5.1+ or PowerShell 7+, local Administrator
                  (to query the WinDefend service and read the Security event log
                  channel reliably), Microsoft Defender Antivirus installed.
    Read-only   : Yes. No Set-MpPreference, no registry writes, no service
                  control actions of any kind.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [ValidateRange(1, 720)]
    [int]$LookbackHours = 24,

    [Parameter(Mandatory = $false)]
    [string]$CsvPath
)

$ErrorActionPreference = 'Stop'
$script:hadError = $false
$script:isHealthy = $true
$findings = [System.Collections.Generic.List[string]]::new()

function Write-Section {
    param([string]$Title)
    Write-Host ""
    Write-Host "[$Title]" -ForegroundColor Cyan
}

Write-Host "Checking Microsoft Defender Antivirus true protection status..." -ForegroundColor White
Write-Host "(This does not change any setting. Read-only checks only.)" -ForegroundColor DarkGray

# ---------------------------------------------------------------------------
# Check 1 - Get-MpComputerStatus (direct read from the Defender engine)
# ---------------------------------------------------------------------------
Write-Section "Get-MpComputerStatus"

$mpStatus = $null
try {
    $mpStatus = Get-MpComputerStatus -ErrorAction Stop
}
catch {
    $script:hadError = $true
    Write-Host "  ERROR: Get-MpComputerStatus failed to run: $($_.Exception.Message)" -ForegroundColor Red
    $findings.Add("Get-MpComputerStatus failed to run - cannot confirm engine-level status.")
}

if ($mpStatus) {
    $amServiceEnabled   = $mpStatus.AMServiceEnabled
    $antivirusEnabled   = $mpStatus.AntivirusEnabled
    $rtpEnabled         = $mpStatus.RealTimeProtectionEnabled
    $onAccessEnabled    = $mpStatus.OnAccessProtectionEnabled
    $runningMode        = $mpStatus.AMRunningMode
    $sigLastUpdated     = $mpStatus.AntivirusSignatureLastUpdated

    Write-Host ("  AMServiceEnabled            : {0}" -f $amServiceEnabled)
    Write-Host ("  AntivirusEnabled             : {0}" -f $antivirusEnabled)
    Write-Host ("  RealTimeProtectionEnabled    : {0}" -f $rtpEnabled)
    Write-Host ("  OnAccessProtectionEnabled    : {0}" -f $onAccessEnabled)
    Write-Host ("  AMRunningMode                : {0}" -f $runningMode)
    Write-Host ("  AntivirusSignatureLastUpdated: {0}" -f $sigLastUpdated)

    if (-not $amServiceEnabled -or -not $antivirusEnabled -or -not $rtpEnabled) {
        $script:isHealthy = $false
        $findings.Add("Get-MpComputerStatus reports one or more protection properties as FALSE - this is a real issue, not the notification bug.")
    }

    if ($runningMode -and $runningMode -ne 'Normal') {
        Write-Host ("  NOTE: AMRunningMode is '{0}', not 'Normal'. This can be expected if a third-party" -f $runningMode) -ForegroundColor Yellow
        Write-Host "        antivirus is the primary engine (Passive Mode) or on an EDR Block Mode device." -ForegroundColor Yellow
        Write-Host "        Confirm this matches your intended configuration; it is not by itself this bug." -ForegroundColor Yellow
    }
}

# ---------------------------------------------------------------------------
# Check 2 - the underlying Windows service (independent of Defender's own
# self-reporting)
# ---------------------------------------------------------------------------
Write-Section "Service: WinDefend"

try {
    $svc = Get-Service -Name WinDefend -ErrorAction Stop
    Write-Host ("  Status: {0}" -f $svc.Status)

    if ($svc.Status -ne 'Running') {
        $script:isHealthy = $false
        $findings.Add("WinDefend service is not Running (Status: $($svc.Status)) - this is a real issue.")
    }
}
catch {
    $script:hadError = $true
    Write-Host "  ERROR: Could not query the WinDefend service: $($_.Exception.Message)" -ForegroundColor Red
    $findings.Add("Could not query the WinDefend service - cannot confirm service-level status.")
}

# ---------------------------------------------------------------------------
# Check 3 - Windows Defender Operational event log, scanning for Event ID
# 5001 (real-time protection disabled) and 5013 (Tamper Protection blocked
# a change) within the lookback window.
# ---------------------------------------------------------------------------
Write-Section "Event log scan - last $LookbackHours hour(s)"

$logName   = 'Microsoft-Windows-Windows Defender/Operational'
$startTime = (Get-Date).AddHours(-1 * $LookbackHours)

try {
    $rtpDisabledEvents = Get-WinEvent -FilterHashtable @{
        LogName   = $logName
        Id        = 5001
        StartTime = $startTime
    } -ErrorAction SilentlyContinue

    $tamperBlockedEvents = Get-WinEvent -FilterHashtable @{
        LogName   = $logName
        Id        = 5013
        StartTime = $startTime
    } -ErrorAction SilentlyContinue

    $rtpDisabledCount    = @($rtpDisabledEvents).Count
    $tamperBlockedCount  = @($tamperBlockedEvents).Count

    if ($rtpDisabledCount -gt 0) {
        Write-Host ("  Event ID 5001 (Real-time protection disabled) : FOUND ({0} occurrence(s))" -f $rtpDisabledCount) -ForegroundColor Red
        $script:isHealthy = $false
        $findings.Add("Event ID 5001 found in the last $LookbackHours hour(s) - real-time protection was genuinely disabled at some point in this window.")
    }
    else {
        Write-Host "  Event ID 5001 (Real-time protection disabled) : NOT FOUND" -ForegroundColor Green
    }

    if ($tamperBlockedCount -gt 0) {
        Write-Host ("  Event ID 5013 (Tamper Protection blocked change): FOUND ({0} occurrence(s))" -f $tamperBlockedCount) -ForegroundColor Yellow
        $findings.Add("Event ID 5013 found in the last $LookbackHours hour(s) - Tamper Protection blocked an attempted change. Review what triggered it.")
    }
    else {
        Write-Host "  Event ID 5013 (Tamper Protection blocked change): NOT FOUND" -ForegroundColor Green
    }
}
catch {
    $script:hadError = $true
    Write-Host "  ERROR: Could not read the Windows Defender Operational event log: $($_.Exception.Message)" -ForegroundColor Red
    $findings.Add("Could not read the Windows Defender Operational event log - cannot confirm event history.")
}

# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------
Write-Host ""
if ($script:hadError) {
    Write-Host "RESULT: ERROR - one or more checks could not run. See messages above." -ForegroundColor Red
    Write-Host "        Fix the reported error and re-run before trusting any HEALTHY/UNHEALTHY result." -ForegroundColor Red
    $exitCode = 2
}
elseif ($script:isHealthy) {
    Write-Host "RESULT: HEALTHY - Defender Antivirus protection is genuinely active." -ForegroundColor Green
    Write-Host "If a 'turned off' notification appeared on this device, it matches" -ForegroundColor Green
    Write-Host "Microsoft's confirmed false-notification bug (release health," -ForegroundColor Green
    Write-Host "opened 2026-08-28). No remediation action required." -ForegroundColor Green
    $exitCode = 0
}
else {
    Write-Host "RESULT: UNHEALTHY - a genuine Defender Antivirus issue was found:" -ForegroundColor Red
    foreach ($finding in $findings) {
        Write-Host ("  - {0}" -f $finding) -ForegroundColor Red
    }
    Write-Host "This is NOT the notification bug. Treat it with your normal incident response." -ForegroundColor Red
    $exitCode = 1
}

if ($CsvPath) {
    try {
        $row = [PSCustomObject]@{
            Timestamp                 = (Get-Date).ToString('s')
            ComputerName               = $env:COMPUTERNAME
            AMServiceEnabled           = if ($mpStatus) { $mpStatus.AMServiceEnabled } else { $null }
            AntivirusEnabled           = if ($mpStatus) { $mpStatus.AntivirusEnabled } else { $null }
            RealTimeProtectionEnabled  = if ($mpStatus) { $mpStatus.RealTimeProtectionEnabled } else { $null }
            AMRunningMode              = if ($mpStatus) { $mpStatus.AMRunningMode } else { $null }
            WinDefendServiceStatus     = if ($svc) { $svc.Status.ToString() } else { $null }
            Event5001FoundInWindow     = $rtpDisabledCount -gt 0
            Event5013FoundInWindow     = $tamperBlockedCount -gt 0
            Result                    = if ($script:hadError) { 'ERROR' } elseif ($script:isHealthy) { 'HEALTHY' } else { 'UNHEALTHY' }
        }
        $csvExists = Test-Path -Path $CsvPath
        $row | Export-Csv -Path $CsvPath -NoTypeInformation -Append:$csvExists
        Write-Host ""
        Write-Host ("Result appended to {0}" -f $CsvPath) -ForegroundColor DarkGray
    }
    catch {
        Write-Host ""
        Write-Host "WARNING: Could not write to CsvPath: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

exit $exitCode
